---
- name: Update apt and install Python3 + pip
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3
    - python3-pip

- name: Install Flask using pip
  pip:
    name: Flask==2.2.2
---
# tasks file for roles/flask_setup
