---
- name: Install PostgreSQL
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2

- name: Start and enable PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create PostgreSQL database
  become_user: postgres
  postgresql_db:
    name: flaskdb

- name: Create PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: flaskuser
    password: flaskpass
    priv: "flaskdb:ALL"
---
# tasks file for roles/postgres_setup
